cmake_minimum_required(VERSION 3.15)

project(StudentLab LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(student
    main.cpp
    CliArgs.cpp
    StudentManager.cpp
)

target_include_directories(student PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/json-develop/include
)